controller_list:
  - name: fake_arm_controller
    joints:
      - base_arm1_Joint
      - arm1_arm2_Joint
      - arm2_arm3_Joint
      - arm3_arm4_Joint
      - arm4_arm5_Joint
      - arm5_arm6_Joint
  - name: fake_gripper_controller
    joints:
      []